srijanone/opendevportal

- profiles/opendevportal/config/install/menu_token.link_configuration_storage.083c4b6f-ede2-4a1e-8eca-a075799941c7.yml
- profiles/opendevportal/config/install/menu_token.link_configuration_storage.4675e8ff-159f-4dc5-a508-63c4210d1501.yml
- profiles/opendevportal/config/install/menu_token.link_configuration_storage.6cdfe795-5931-4a28-8227-f3bd599741e3.yml
- profiles/opendevportal/config/install/menu_token.link_configuration_storage.9e86ae8b-b93f-4009-bcc5-c95b4cb32ae4.yml
- profiles/opendevportal/config/install/menu_token.link_configuration_storage.a7060da3-7787-444d-9c07-fe5827271138.yml
- profiles/opendevportal/config/install/menu_token.link_configuration_storage.f19d113e-d586-4580-a285-099656ccbf2b.yml
ODX-profile-hotfix: Added menu token configs
> ODX-profile-hotfix: Added menu token configs

- profiles/opendevportal/modules/custom/odp_demo/content/group_content/ee757bda-ab6c-41be-9150-6ff915a3edf5.yml
- profiles/opendevportal/modules/custom/odp_demo/content/menu_link_content/17d7710e-b2ff-470d-b578-94869cb16327.yml
- profiles/opendevportal/modules/custom/odp_demo/content/node/a38d431e-2353-4958-98c4-117f22ecd855.yml
ODX-profile-hotfix: Updated the MENU menu item.
> ODX-profile-hotfix: Updated the MENU menu item

- profiles/opendevportal/config/install/block.block.account_menu.yml
ODX-profile-hotfix: Added an account-menu and remove the older one
> ODX-profile-hotfix: Added a account-menu and remove older one

- profiles/opendevportal/config/install/views.view.programs.yml
- profiles/opendevportal/config/install/views.view.proxies_listing.yml
Updated the url for api sync and sync CTAs
> Updated the url for api sync and sync CTAs

- profiles/opendevportal/modules/custom/odp_demo/content/group_content/51a0f386-7221-4767-8858-d272a9605c60.json
- profiles/opendevportal/modules/custom/odp_demo/content/group_content/bb734b59-7f0b-4f11-a37b-887f473aa8d0.json
- profiles/opendevportal/modules/custom/odp_demo/content/node/44d1921b-6a37-40b0-8d6b-df66d8939683.json
- profiles/opendevportal/modules/custom/odp_demo/content/node/c62f5bec-9f0c-4972-ba63-a2851b972af9.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/0d7dcb20-da6d-4340-a8c4-da9e25380ca4.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/2b1d60fd-0863-4d40-adcf-84a05189e526.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/4326434a-6c95-4392-9992-35c79db6924d.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/565030a7-9a37-4a54-b3f8-45f44b8f1296.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/8f1ee304-d1ea-4ed7-a924-76ce8cb0fca7.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/998b38cc-3468-42ae-bded-e0090629737f.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/9fa569d1-4737-4034-800d-c244608fe303.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/bbf18510-7d0d-442e-9532-43a45ac93654.json
- profiles/opendevportal/modules/custom/odp_demo/content/taxonomy_term/e0bb72d4-04fd-4fde-8d6e-f2a72c141d29.json
- profiles/opendevportal/modules/custom/odp_demo/odp_demo.info.yml
ODX-profile-hotfix: added a solution and issues content
> ODX-profile-hotfix: added a solution and issues content

- profiles/opendevportal/modules/custom/odp_demo/content/group_content/26340802-6049-449d-bba1-d7f8a582d3d7.json
- profiles/opendevportal/modules/custom/odp_demo/content/group_content/67e6d1ed-6278-4915-baa8-c3b36028786b.json
- profiles/opendevportal/modules/custom/odp_demo/content/user/0f3fa4ea-3feb-400f-9bf0-62ffb8b891d6.json
- profiles/opendevportal/modules/custom/odp_demo/content/user/5351aa1e-7e62-4d9e-9099-3198846b2cbe.json
- profiles/opendevportal/modules/custom/odp_demo/content/user/5bd739b8-6995-431c-9a04-889c295045d2.json
- profiles/opendevportal/modules/custom/odp_demo/odp_demo.info.yml
ODX-profile-hotfix: added 3 users
> ODX-profile-hotfix: added 3 users

- profiles/opendevportal/config/install/block.block.page_title.yml
ODX-profile-hotfix: remove the content listing block title from content listing pages
> ODX-profile-hotfix: remove the content listing block title

- profiles/opendevportal/config/install/block.block.main_menu.yml
- profiles/opendevportal/config/install/block.block.page_title.yml
ODX-profile-hotfix: update the main navigation block
> ODX-profile-hotfix: update the main navigation block

- profiles/opendevportal/modules/custom/odp_demo/odp_demo.info.yml
ODX-profile-hotfix: Updated the images in all the nodes
> ODX-profile-hotfix: Updated the images in all the nodes

- config/install/block.block.breadcrumbs.yml
ODX-breadcrumb-hotfix: Update the breadcrumb block
> ODX-breadcrumb-hotfix: Update the breadcrumb block

- themes/custom/devportal_admin/css/style.css
ODX-bugs: Resolved the user menu icon missing images.
> ODX-bugs: Resolved the user menu icon missing images.

- modules/custom/odp_core/odp_core.module
- modules/custom/odp_node/odp_node.module
- modules/custom/odp_node/odp_node.routing.yml
- modules/custom/odp_node/odp_node.services.yml
- modules/custom/odp_workflow/README.md
- modules/custom/odp_workflow/odp_workflow.info.yml
- modules/custom/odp_workflow/odp_workflow.module
- modules/custom/odp_workflow/odp_workflow.routing.yml
- modules/custom/odp_workflow/odp_workflow.services.yml
- modules/custom/odp_workflow/src/Controller/NextModerationState.php
- modules/custom/odp_workflow/src/Routing/RouteSubscriber.php
- opendevportal.info.yml
ODP-000: Create workflow module to store all features related to it.
> ODP-000: Create workflow module to store all features related to it.

- modules/custom/odp_block/odp_block.module
- modules/custom/odp_paragraph/odp_paragraph.services.yml
- modules/custom/odp_product/odp_product.module
- modules/custom/odp_product/odp_product.services.yml
- modules/custom/odp_product/src/Paragraph.php
- modules/custom/odp_product/src/Plugin/Block/ProductBannerBlock.php
- modules/custom/odp_product/templates/product-banner.html.twig
Please review the PR and merge it.
> cleanup paragraph module with block and added in product module

- opendevportal.info.yml
ODX-remove-modules: Removed unused modules from info.yml
> ODX-remove-modules: Removed unused modules from info.yml

- composer.json
ODX-remove-modules: added a lazysizes library
> ODX-remove-modules: added a lazysizes library

- composer.json
- modules/custom/odp_subscription/odp_subscription.module
ODX-remove-modules: Update the token syntax
> ODX-remove-modules: Update the token syntax

- themes/custom/devportal_admin/js/custom.js
- themes/custom/opendevx_theme/assets/css/base.css
- themes/custom/opendevx_theme/assets/css/page-node.css
- themes/custom/opendevx_theme/components/01-base/headings/_headings.scss
- themes/custom/opendevx_theme/components/05-templates/page-node/page-node.scss
ODX-remove-modules: Issue fixing
> ODX-remove-modules: Issue fixing

- modules/custom/odp_demo/content/menu_link_content/17d7710e-b2ff-470d-b578-94869cb16327.json
- modules/custom/odp_demo/content/node/71ebc8c4-ba5d-4d79-b8af-39655e79ea03.json
- modules/custom/odp_demo/content/node/f0113c45-3647-4059-a1cf-ceb6b08b82ef.json
ODX-remove-modules: Update the menu item and landing page of use case and solutions
> ODX-remove-modules: Update the menu item and landing page

- config/install/pathauto.pattern.application.yml
ODP:000: Created path alias pattern for application.
> ODP:000: Created path alias pattern for application.

- modules/custom/odp_base/odp_base.module
> hide-local-tabs-search

- modules/custom/odp_product/odp_product.info.yml
> Changed the module title for the product

- composer.json
ODP-000: Added libraries inside profile composer file.
> ODP-000: Added libraries inside profile composer file.

- modules/custom/odp_demo/content/file/74373b95-5e8c-4ca9-a0b4-58c3d024ce1b.json
- modules/custom/odp_demo/content/file/8f319866-4675-4bde-acef-2d977666ea6e.json
- modules/custom/odp_demo/content/file/d93f64ad-5f0c-4e4b-b84b-facafc9a22a4.json
- modules/custom/odp_demo/content/node/00b01f64-258c-4fdf-9c1f-e2b92f0adaa1.json
- modules/custom/odp_demo/content/node/d346809a-12e3-4980-bc4c-f68d0ae4eb1f.json
- modules/custom/odp_demo/content/user/0f3fa4ea-3feb-400f-9bf0-62ffb8b891d6.json
- modules/custom/odp_demo/content/user/5351aa1e-7e62-4d9e-9099-3198846b2cbe.json
- modules/custom/odp_demo/content/user/5bd739b8-6995-431c-9a04-889c295045d2.json
- modules/custom/odp_demo/odp_demo.info.yml
- modules/custom/odp_product/modules/odp_forum/odp_forum.install
- modules/custom/odp_product/modules/odp_forum/odp_forum.module
ODX-remove-modules: Added a user image
> ODX-remove-modules: Added a user image

- modules/custom/odp_api_documents/modules/odp_sdk/odp_sdk.module
- modules/custom/odp_api_documents/modules/odp_sdk/src/Plugin/Block/DownloadSdk.php
- modules/custom/odp_api_documents/modules/odp_sdk/templates/sdk-card.html.twig
> 8.x: SDK markup issue fixed

- config/install/system.site.yml
- themes/custom/opendevx_theme/opendevx_theme.theme
access-denied: Update the access-denied page path.
> access-denied: Update the access-denied page path

- modules/custom/odp_api_documents/modules/odp_sdk/src/Plugin/Block/DownloadSdk.php
- modules/custom/odp_apps/src/Controller/CtaAppsController.php
- modules/custom/odp_base/modules/odp_blocks/src/Form/ApiFilterForm.php
- modules/custom/odp_base/modules/odp_blocks/src/Plugin/Block/ProductHeaderNavigationBlock.php
- modules/custom/odp_base/modules/odp_blocks/src/Utility/ApiFilterationUtility.php
- modules/custom/odp_base/modules/odp_blocks/src/Utility/BlockUtility.php
- modules/custom/odp_base/modules/odp_breadcrumb/src/Utility/BreadcrumbUtility.php
- modules/custom/odp_notification/src/Services/OdpNotificationService.php
- modules/custom/odp_product/modules/odp_issue/src/Controller/CtaController.php
- modules/custom/odp_product/src/Plugin/Block/ProductBannerBlock.php
- modules/custom/odp_user/modules/odp_login_redirect/src/Redirect.php
- modules/custom/odp_user/src/Plugin/Block/UserOrganisationBlock.php
Fixed all the warnings and notices from all the modules.
> Fixed all the warnings and notices from all the modules.

- config/install/core.entity_view_display.node.api_product.full.yml
- modules/custom/odp_demo/content/block_content/bef7e39a-3e3c-48d5-87b9-45dbacb2e57c.json
- modules/custom/odp_demo/content/node/00b01f64-258c-4fdf-9c1f-e2b92f0adaa1.json
- modules/custom/odp_demo/content/node/44d1921b-6a37-40b0-8d6b-df66d8939683.json
- modules/custom/odp_demo/content/node/a56319f8-a591-407d-97a3-0d4064d5518f.json
- modules/custom/odp_demo/content/node/c0744688-0a20-40bc-9afb-a530f0ce11ea.json
- modules/custom/odp_demo/content/node/f9eb2841-5a6a-4d51-b046-2bf9f95f85a0.json
- modules/custom/odp_demo/content/taxonomy_term/97a2de6b-2292-4f79-a30e-473c6b4fa126.json
- modules/custom/odp_demo/content/taxonomy_term/a8b5cc30-7f5b-48c4-ba8a-ad80ea6fd283.json
- modules/custom/odp_demo/odp_demo.info.yml
update-demo-content: Updated the demo contents
> update-demo-content: Updated the demo contents

- modules/custom/odp_api_documents/modules/odp_renderer/README.md
- modules/custom/odp_api_documents/modules/odp_renderer/modules/odp_asyncapi/css/index.css
- modules/custom/odp_api_documents/modules/odp_renderer/modules/odp_rapidoc_formatter/odp_rapidoc_formatter.info.yml
- modules/custom/odp_api_documents/modules/odp_renderer/modules/odp_rapidoc_formatter/src/Plugin/Block/ApiFormatterOptionsBlock.php
- modules/custom/odp_api_documents/modules/odp_renderer/modules/odp_voyager/odp_voyager.info.yml
- modules/custom/odp_api_documents/modules/odp_renderer/modules/odp_voyager/src/Plugin/Field/FieldFormatter/VoyagerUIFormatter.php
- modules/custom/odp_api_documents/modules/odp_renderer/odp_renderer.info.yml
- modules/custom/odp_api_documents/modules/odp_sdk/README.md
- modules/custom/odp_api_documents/modules/odp_sdk/odp_sdk.info.yml
- modules/custom/odp_api_documents/modules/odp_sdk/odp_sdk.services.yml
- modules/custom/odp_api_documents/modules/odp_sdk/src/Form/DownloadSdk.php
- modules/custom/odp_api_documents/modules/odp_sdk/src/Utility/GenerateSdk.php
- modules/custom/odp_api_documents/odp_api_documents.module
Please review the PR @mayurjadhav
> 8.x: Improved code quality for module api documents

- modules/custom/odp_apps/odp_apps.module
- modules/custom/odp_apps/odp_apps.routing.yml
- modules/custom/odp_apps/src/Controller/AppManagementController.php
- modules/custom/odp_apps/src/Controller/CtaAppsController.php
Please review the PR @mayurjadhav
> 8.x: improved code for apps module

- modules/custom/odp_api_documents/modules/odp_sdk/odp_sdk.info.yml
Please merge this pr @mayurjadhav
> sdk: added dependency of user module

- modules/custom/odp_notification/odp_notification.module
- modules/custom/odp_notification/src/Form/OdpNotificationForm.php
- modules/custom/odp_notification/src/Plugin/Action/OdpNotificationAction.php
- modules/custom/odp_notification/src/Plugin/Block/OdpNotificationBlock.php
- modules/custom/odp_notification/src/Services/OdpNotificationService.php
ODP:Updated the odp_notification module code.
> ODP:Updated the odp_notification module code.

- modules/custom/odp_subscription/odp_subscription.install
- modules/custom/odp_subscription/src/Services/SubscriptionQueue.php
- modules/custom/odp_subscription/src/SubscriptionContent.php
- modules/custom/odp_subscription/src/Utility/SubscriptionUtility.php
ODP: Updated subscription module code.
> ODP: Updated subscription module code.

- modules/custom/odp_user/modules/odp_login_redirect/src/Form/SettingsBaseForm.php
- modules/custom/odp_user/src/EventSubscriber/FormAlterSubscriber.php
- modules/custom/odp_user/src/Plugin/Block/UserOrganisationBlock.php
- modules/custom/odp_user/src/Plugin/Block/UserProgramsBlock.php
ODP: Updated subscription module code.
> ODP: Updated odp user module code.

- modules/custom/odp_subscription/odp_subscription.module
- modules/custom/odp_subscription/odp_subscription.services.yml
- modules/custom/odp_subscription/src/Services/SubscriptionUtility.php
ODP: Moved SubscriptionUtility file to services and added new service to access the methods.
> ODP: Moved SubscriptionUtility file to services and added new service to access the methods.

- modules/custom/odp_subscription/src/SubscriptionContent.php
ODP: fixed sunscription content constructor arguments issue.
> ODP: fixed sunscription content constructor arguments issue.

- modules/custom/odp_program/README.md
- modules/custom/odp_program/modules/odp_domain/README.md
- modules/custom/odp_program/modules/odp_domain/src/Plugin/views/field/ProgramDomainHost.php
- modules/custom/odp_program/src/Utility/ProgramUtility.php
ODP: Updated odp program module code.
> ODP: Updated odp program module code.

- modules/custom/odp_demo/content/menu_link_content/2cf2453e-a737-486f-af0e-60a5fa27d63d.json
- modules/custom/odp_demo/content/menu_link_content/840ba278-f0ac-4fea-8b72-5e85224bc532.json
update-demo-content: Updated the menu links
> update-demo-content: Updated the menu links

- modules/custom/odp_product/modules/odp_forum/src/Plugin/Block/ForumStats.php
- modules/custom/odp_product/modules/odp_forum/src/Plugin/Block/TopTags.php
- modules/custom/odp_product/modules/odp_issue/src/Controller/CtaController.php
- modules/custom/odp_product/odp_product.module
- modules/custom/odp_product/src/Plugin/Block/ProductBannerBlock.php
ODP: Updated the odp product and sub modules.
> ODP: Updated the odp product and sub modules.

- modules/custom/odp_base/modules/odp_blocks/src/Utility/BlockUtility.php
ODP:fixed program switcher block issue.
> ODP:fixed program switcher block issue.

- config/install/views.view.events.yml
- config/install/views.view.forum.yml
- modules/custom/odp_base/odp_base.module
- modules/custom/odp_program/odp_program.module
- modules/custom/odp_user/odp_user.module
ODP: Added local task tabs to siteadmin and added no result found text to events and forum view.
> ODP: Added local task tabs to siteadmin and added no result found text to events and forum view.
